services:
  db:
    container_name: postgres
    image: postgres:16.1
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
  file:
    container_name: file
    build: ./upload/
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static-content:/usr/src/app/uploads
  processing:
    container_name: processing
    build: ./process/
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static-content:/usr/src/app/uploads
volumes:
  static-content: