version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:16.1
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
  web:
    container_name: upload
    build: ./upload/
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy