ktor:
  application:
    modules:
      - utm.ass.project_m.ApplicationKt.module
  deployment:
    port: 8080

postgres:
  url: $POSTGRES_URL
  user: $POSTGRES_USER
  password: $POSTGRES_PASSWORD